server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ec2-23-23-151-191.compute-1.amazonaws.com:5432/db02re0k3o8016
    username: tevebayzhitlms
    password: 43915632e8c2fe63226f725df0bc076c1712c5d5a9559fcece3dde64e41d1d7d
  jpa:
    hibernate:
      ddl-auto: update
#          ddl-auto: create
    show-sql: true
    open-in-view: true






